//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiuShiBaiKe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageComment
    {
        public long Id { get; set; }
        public long MessageId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long UserId { get; set; }
        public string Comment { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
